
package services.globalpay;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param uid
     * @param merchantID
     * @param endDate
     * @param channel
     * @param pwd
     * @param merchTxnref
     * @param startDate
     * @param paymentStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "https://www.eazypaynigeria.com/globalpay/getTransactions")
    @WebResult(name = "getTransactionsResult", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "https://www.eazypaynigeria.com/globalpay/", className = "https.www_eazypaynigeria_com.globalpay.GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "https://www.eazypaynigeria.com/globalpay/", className = "https.www_eazypaynigeria_com.globalpay.GetTransactionsResponse")
    public String getTransactions(
            @WebParam(name = "merch_txnref", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String merchTxnref,
            @WebParam(name = "channel", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String channel,
            @WebParam(name = "merchantID", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String merchantID,
            @WebParam(name = "start_date", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String startDate,
            @WebParam(name = "end_date", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String endDate,
            @WebParam(name = "uid", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String uid,
            @WebParam(name = "pwd", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String pwd,
            @WebParam(name = "payment_status", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String paymentStatus);

    /**
     * 
     * @param uid
     * @param amount
     * @param merchantid
     * @param currency
     * @param fieldDetails
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "https://www.eazypaynigeria.com/globalpay/postTransactionGlobalPay")
    @WebResult(name = "postTransactionGlobalPayResult", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
    @RequestWrapper(localName = "postTransactionGlobalPay", targetNamespace = "https://www.eazypaynigeria.com/globalpay/", className = "https.www_eazypaynigeria_com.globalpay.PostTransactionGlobalPay")
    @ResponseWrapper(localName = "postTransactionGlobalPayResponse", targetNamespace = "https://www.eazypaynigeria.com/globalpay/", className = "https.www_eazypaynigeria_com.globalpay.PostTransactionGlobalPayResponse")
    public String postTransactionGlobalPay(
            @WebParam(name = "merchantid", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String merchantid,
            @WebParam(name = "amount", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            BigDecimal amount,
            @WebParam(name = "currency", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String currency,
            @WebParam(name = "field_details", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String fieldDetails,
            @WebParam(name = "uid", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String uid,
            @WebParam(name = "pwd", targetNamespace = "https://www.eazypaynigeria.com/globalpay/")
            String pwd);

}
